name: CI/CD to Local WSL

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-local:
    # This tells GitHub to send the job to your local machine
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-web-app:latest .

    - name: Deploy Docker container
      run: |
        # Stop and remove the old container if it exists
        docker stop webapp || true
        docker rm webapp || true
        # Run the new container
        docker run -d --name webapp -p 8080:80 my-web-app:latest
